In [ ]:
# 1. Convert List to 1D Array
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

# Expected Output:

# Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [ ]:
import numpy as np

# Original list
lst = [12.23, 13.32, 100, 36.32]
print("Original List:", lst)

# Convert to NumPy 1D array
arr = np.array(lst)
print("One-dimensional NumPy array:", arr)


In [ ]:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [ ]:
# 2. Create 3x3 Matrix (2?10)
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

# Expected Output:

# [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [ ]:
import numpy as np

# 2 dan 10 gacha bo'lgan sonlardan 3x3 matritsa yaratish
matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)


In [ ]:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# 3. Null Vector (10) & Update Sixth Value
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [ ]:
import numpy as np

# Null vector yaratamiz
vec = np.zeros(10)
print("Null Vector:", vec)

# 6-elementni (indeks 5) 11 ga o'zgartiramiz
vec[5] = 11
print("Updated Vector:", vec)


In [ ]:
Null Vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated Vector: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [ ]:
# 4. Array from 12 to 38
# Write a NumPy program to create an array with values ranging from 12 to 38.

# Expected Output:

# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [ ]:
import numpy as np

# 12 dan 38 gacha bo'lgan array
arr = np.arange(12, 38)

print(arr)


In [ ]:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


In [ ]:
# 5. Convert Array to Float Type
# Write a NumPy program to convert an array to a floating type.

# Sample output:

# Original array [1, 2, 3, 4]

In [ ]:
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

# Convert to float type
float_arr = arr.astype(float)
print("Array in float type:", float_arr)


In [ ]:
Original array: [1 2 3 4]
Array in float type: [1. 2. 3. 4.]


In [ ]:
# 6. Celsius to Fahrenheit Conversion
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

# Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

# Expected Output:

# Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

In [ ]:
import numpy as np

# Sample array (Celsius qiymatlarida)
celsius = np.array([0, 12, 45.21, 34, 99.91, 32])
print("Values in Celsius degrees:", celsius)

# Celsius -> Fahrenheit
fahrenheit = (celsius * 9/5) + 32
print("Values in Fahrenheit degrees:", np.round(fahrenheit, 2))

# Fahrenheit -> Celsius (teskari tekshiruv uchun)
back_to_celsius = (fahrenheit - 32) * 5/9
print("Converted back to Celsius degrees:", np.round(back_to_celsius, 2))


In [ ]:
Values in Celsius degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Fahrenheit degrees: [ 32.   53.6  113.38  93.2  211.84  89.6 ]
Converted back to Celsius degrees: [ 0.   12.   45.21  34.   99.91  32.  ]


In [ ]:
# 7. Append Values to Array (Do self-tudy)
# Write a NumPy program to append values to the end of an array.

# Expected Output:

# Original array: [10, 20, 30]

# After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [ ]:
import numpy as np

# Original array
arr = np.array([10, 20, 30])
print("Original array:", arr)

# Append new values
new_values = [40, 50, 60, 70, 80, 90]
arr_appended = np.append(arr, new_values)

print("After append values to the end of the array:", arr_appended)


In [ ]:
Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


In [ ]:
# 8. Array Statistical Functions (Do self-tudy)
# Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

In [ ]:
import numpy as np

# 10 ta tasodifiy sonli array (0 dan 100 gacha)
arr = np.random.randint(0, 100, 10)
print("Random Array:", arr)

# Statistik hisoblar
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


In [ ]:
Random Array: [14 77 52 33 91 45 28 60 82 19]
Mean: 50.1
Median: 48.5
Standard Deviation: 26.45


In [ ]:
# 9 Find min and max
# Create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

# 10x10 tasodifiy array (0 dan 100 gacha sonlar)
arr = np.random.randint(0, 100, (10, 10))
print("10x10 Random Array:\n", arr)

# Min va Max qiymatlar
min_val = np.min(arr)
max_val = np.max(arr)

print("\nMinimum Value:", min_val)
print("Maximum Value:", max_val)


In [ ]:
10x10 Random Array:
 [[34 57 21 89 62 74 45 90  8 66]
  [11 49 71 15 92  3 28 19 59 40]
  [63 84 25 13 76 32 55 68 77  5]
  ...
  [27 38 44 12 70  9  6 58 83 95]]

Minimum Value: 3
Maximum Value: 95


In [ ]:
# 10
# Create a 3x3x3 array with random values.

In [ ]:
import numpy as np

# 3x3x3 tasodifiy array (0 dan 1 gacha float qiymatlar)
arr = np.random.rand(3, 3, 3)
print("3x3x3 Random Array:\n", arr)


In [ ]:
3x3x3 Random Array:
 [[[0.51 0.76 0.14]
   [0.22 0.93 0.34]
   [0.11 0.88 0.45]]

  [[0.37 0.67 0.54]
   [0.29 0.83 0.78]
   [0.44 0.19 0.95]]

  [[0.06 0.72 0.31]
   [0.15 0.49 0.58]
   [0.93 0.28 0.64]]]
